### ISSUE TITLE
Question about format

### ISSUE THREAD

**Issue by mmcardle** [buzz/mediainfo.js#16]
Hello, great library, is there a way to change the format to JSON. e.g.
```
miLib = MediaInfo(function() {
   mi = new miLib.MediaInfo({"Output: "JSON"});
})
```

I see there is an option to change the output in https://github.com/buzz/mediainfo.js/blob/master/mediainfojs.cpp
```
MediaInfoJs() {
    mi.Option(__T("Output"), __T("XML"));
    mi.Option(__T("File_IsSeekable"), __T("1"));
  }
```

but can't quite figure out how to make it work

Thanks

**Comment by tumidi** [comment]
As far as I know MediaInfo only supports XML output. On the demo page I use a XML2JSON lib: https://github.com/abdmob/x2js

**Comment by buzz** [comment]
As far as I know MediaInfo only supports XML output. On the demo page I use a XML2JSON lib: https://github.com/abdmob/x2js

**Comment by JeromeMartinez** [comment]
> As far as I know MediaInfo only supports XML output. 

The line `mi.Option(__T("Output"), __T("XML"));` is there because this is not the default output, so "only supports XML output" is wrong ;-) (remove this line and you'll get the text output; there are a couple of other output formats).

About JSON: we (MediaInfo library developers) added JSON output in the library few months ago (IIRC after the last commit in this repo, so this is normal that this repo uses the XML output then convert XML to JSON), `mi.Option(__T("Output"), __T("JSON"));` will provide a JSON output without needing a XML2JSON lib, but there may need some development for handling the native JSON output.
Note that [there is a discussion about changing JSON output](https://github.com/MediaArea/MediaInfo/issues/243), so the JSON output may change (incompatible change) in a near future.

**Comment by buzz** [comment]
Yes, you're right. This wasn't accurate.

Closing as questions seems to be sufficiently answered.
