### ISSUE TITLE
Build issue where 'Lines_MaxCharacterCount' is not found

### ISSUE THREAD

**Issue by arjenxdevries** [buzz/mediainfo.js#162]
### Checklist

- [ x] I have searched the issue tracker for any duplicate issues and confirmed that this bug has not been reported before.
- [ x] I have tested the issue with the upstream project [MediaInfo](https://github.com/MediaArea/MediaInfoLib) and can confirm that the problem only exists in mediainfo.js.
- [ x] I have attached all necessary test files, if applicable, so that the issue can be easily reproduced by the developers.
- [ ] I have added a reproduction repository or a code sandbox that clearly illustrates the issue. Providing a minimal example will greatly help the developers in understanding and resolving the problem.

### Steps to Reproduce

1.  building the project results in this error:
"Error: Property 'Lines_MaxCharacterCount' not found XSD"
3. ...
4. ...

### Environment

- mediainfo.js version: [e.g. 1.2.3]
- Operating System: [e.g. Windows 10, macOS Big Sur]
- Browser (if applicable): [e.g. Chrome 90, Firefox 87]
- Node.js (if applicable): [e.g. 18.16.0]

### Additional Information

In investigating this build error, we noticed that https://github.com/MediaArea/MediaInfoLib/blob/master/Source/Resource/Text/Stream/Text.csv recently had some changes merged to master branch including "Lines_MaxCharacterCount;;;Y YTY;;;;;" 

in this file ./gulp/generate-types/data/parseCsv.ts, we could see it was referencing the master branch version like this:

"  `https://raw.githubusercontent.com/MediaArea/MediaInfoLib/master/Source/Resource/Text/Stream/${type}.csv`"

When we changed to a versioned url, it worked for us.

**Comment by JeromeMartinez** [comment]
This is an issue for https://github.com/MediaArea/MediaAreaXml/issues, not yet updated compared to MediaInfoLib master branch.
(I'll add `https://github.com/MediaArea/MediaAreaXml/issues` to the XSD soon)

**Comment by ulibocchio** [comment]
First off, thank you this library, great work.
You can future proof this by simply using the CVSs from the media info source download during build (`https://mediaarea.net/download/source/${libname}/${version}/${libname}_${version}.tar.bz2`), instead of pulling the CSVs from the master branch of the source repo.

To future proof XSD  changes, I think it would be best to use the officially published XSD from here: https://mediaarea.net/mediainfo/mediainfo_2_0.xsd, rather from the gitlab master branch.
Which according to the [MediaInfoLib source](https://github.com/MediaArea/MediaInfoLib/blob/dbed0279c05911f50f9ad715d187666e38f8764c/Source/MediaInfo/MediaInfo_Internal.cpp#L2695), that's where it references it from.

**Comment by JeromeMartinez** [comment]
> To future proof XSD changes, I think it would be best to use the officially published XSD from here: https://mediaarea.net/mediainfo/mediainfo_2_0.xsd, rather from the gitlab master branch.

I update the [GitHub XSD file](https://github.com/MediaArea/MediaAreaXml/blob/master/mediainfo.xsd) first but public link is usually updated few seconds after it.

> You can future proof this by simply using the CVSs

I forgot (again) the XSD but I expect that both the XSD and the CSV are fine. The CSV has the advantage to permit to filter per stream kind.

**Comment by ulibocchio** [comment]
thank you!
