### ISSUE TITLE
Image Size Error

### ISSUE THREAD

**Issue by jcald1** [buzz/mediainfo.js#18]
I ran the media info script on a PNG of size 1000X684.  The resulting object contains:

```
  "Width": [
    "1000",
    "1 000 pixels"
  ],
  "Height": [
    "684",
    "684 pixels"
  ],
```

The width is "1 000 pixels".  It has a space where a comma should be.  Should this be a human-readable field using commas?  It would be useful to have a property with just the number (1000), a property with the units (pixels) and a property that is human-readable (1,000 pixels)

**Comment by JeromeMartinez** [comment]
> The width is "1 000 pixels". It has a space where a comma should be.

This "should" is not universal nor standard, just an usage in some countries (but the output can be displayed everywhere on the world, so the JS script should ask the country for adapting the output, copied by a person who uses the comma as a thousands separator then sent to a person who uses the comma as a decimal separator...)

> Should this be a human-readable field using commas?

"human-readable" does not mean "by some humans only, and other humans will have issues", the space as thousands separator avoids this split between humans. [See all countries using comma as a decimal separator](https://en.wikipedia.org/wiki/Decimal_separator#/media/File:DecimalSeparator.svg).

https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping
"Since 2003, the use of spaces as separators (for example: 20 000 and 1 000 000 for "twenty thousand" and "one million") has been officially endorsed by SI/ISO 31-0 standard, as well as by the International Bureau of Weights and Measures and the International Union of Pure and Applied Chemistry (IUPAC), the American Medical Association's widely followed AMA Manual of Style, and the Metrication Board, among others."

Note: if despite international standards, including American ones, the developer wants to modify default behavior, this line of code (to be adapted to JS) can be used for setting the thousands separator to comma:
`MediaInfo::Option("Language", "  Config_Text_ThousandsSeparator;,");`
