### ISSUE TITLE
PSD is considered as an audio file in version 0.1.5

### ISSUE THREAD

**Issue by jearyvon** [buzz/mediainfo.js#62]
![image](https://user-images.githubusercontent.com/12572920/116022256-6c6a6680-a67c-11eb-97dc-6222a426e0fb.png)

**Comment by buzz** [comment]
Did you try [MediaInfo](https://mediaarea.net/de/MediaInfo) to make sure this is indeed an issue with mediainfo.js?

**Comment by jearyvon** [comment]
> Did you try [MediaInfo](https://mediaarea.net/de/MediaInfo) to make sure this is indeed an issue with mediainfo.js?


I found that this problem occurs when chunksize is set to 1024 * 1024 * 2

![image](https://user-images.githubusercontent.com/12572920/116389657-c53e2880-a84f-11eb-8c4c-177617353a49.png)

**Comment by JeromeMartinez** [comment]
> chunksize is set to 1024 * 1024 * 2

So issue in the MediaInfo library (not in the mediainfo.js glue).
We know that there are some issues there, lack of time for handling them :(.
But I (MediaInfo library developer) am interested in getting the file for including it in my test repository (in order to be sure the issue is fixed and no regression in the future) when I have enough time for fixing it.
