### ISSUE TITLE
Server-side rendering (SSR)

### ISSUE THREAD

**Issue by lonkaars** [buzz/mediainfo.js#78]
I've already tried the troubleshooting steps from #38 since I'm using react, but with next.js. I've also tried using next.config.js instead of webpack.config.js but both don't seem to work.

the error comes from `node_modules/mediainfo.js/dist/mediainfo.js:40:905`

I believe Next.js uses nodejs to render server-side first, and then switches to browser-only js which is probably why it's freaking out. Is there maybe some way to disable `fs` and `path` inside mediainfo.js or is next.js compatibility not supported at all?

**Comment by buzz** [comment]
The challenge in SSR is, you need to make sure, all code, including all libs you're using, feel well in both environments (Node.js and browser) using the very same codebase. Otherwise you will encounter problems. This particular lib does support both these environments.

You can see working examples for both environments: [Node.js](https://github.com/buzz/mediainfo.js/blob/master/src/cli.ts) and [Browser/webpack](https://github.com/buzz/mediainfo.js/blob/gh-pages-src/src/components/MediaInfoJs.js).

Your challenge is now to create a single example which runs both on Node and in the browser. I'd suggest creating a minimal test repository for this, e. g. using Next.js. If you need help achieving this, I suggest reading into SSR and/or asking on SO. I'd be very happy to link such a minimal SSR-enabled test repository in the README of this project.

Unfortunately you provided very little info with this issue. Depending on your requirements it might be sufficient to simply skip the library server-side (or client-side). But without having more information, I'm unable to help you.

**Comment by lonkaars** [comment]
[Here's](https://codesandbox.io/s/optimistic-taussig-7mgdd?file=/pages/index.js) a minimal working example. The way Next.js works is it runs the first react render on the server (using node.js).

I think it's a problem with the typescript compiler because I looked through the source here on github and didn't see any `fs` or `path` imports outside the cli (which i'm not using). The compiled mediainfo.js sets a variable `ENVIRONMENT_IS_NODE` if `typeof process === "object"` which evaluates to `true` on the first render with next.js.

I could try importing the browser library by adding tags to the `<head>` element but that seems like a janky solution to me...

**Comment by buzz** [comment]
Next.js is using webpack under the hood. The error is because webpack will try import `fs` which is not available in the browser environment. This has been discussed in length already in #38 and [this particular post is the solution to your problem.](https://github.com/buzz/mediainfo.js/issues/38#issuecomment-780558245)

Nevertheless, as there's still an actual issue with SSR, I will leave this open for now.

**Comment by lonkaars** [comment]
Using `next/head` to import the library vanilla-style works, but I'm still looking for a 'cleaner' solution to this. I've also found `next/dynamic` which should let you import libraries only on the client side, but it still gives me the same error so I'll try hacking at it some more and I'll post a better solution here if I find one.

**Comment by buzz** [comment]
Please refrain from discussing programming practices regarding Next.js here. Your question has been answered already. If you need further advice to tackle your problem, please ask your questions at Stack Overflow.
