### ISSUE TITLE
RangeError: WebAssembly.instantiate(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by dodomorandi** [buzz/mediainfo.js#91]
I encountered this bug using a NextJS backend, and it is pretty tricky.

First of all, I really believe this is not related to this library, but I am still opening the issue because I am not sure about the possible cause.

The bug is not triggered every time, but it looks like that, after some instantiations of `MediaInfo` in the same Node process, the OOM behavior seems to be consistent. The issue can be reproduced modifying `file_example_MP4_640_3MG.mp4.test.js`, using `expect.hasAssertions()` instead of `expect.assertions(77)`, adding a `mi.close()` after the call to `analyzeFile` and putting everything inside a `for (;;) { /* ... */ }` (with the exception of `expect.hasAssertions()`).

Thankfully enough, hacking the code I discovered that `MediaInfo` can be used without the callback, so I can drastically reduce the number of instantiations. However, I feel that the problem is still there and it should be solved.

If anyone is able to track down the origin to any of the dependencies (or inside this lib, but I have my doubts), it would be great.

**Comment by jimmy1231** [comment]
I am facing a similar issue running MediaInfoJS on Node 12 AWS Lambda to process some media files: after consecutive invocations each instantiating a new instance of Mediainfo I get OOM and the Lambda crashes. I fixed it using a similar approach by moving the instantiation of MediaInfo to module level, and doing something like this to get it

```javascript
const MediaInfoJS = require("mediainfo.js");

let MEDIA_INFO_JS = null;

...

async function getMediaInfoJS () {
  if (!_.isNil(MEDIA_INFO_JS)) {
    return MEDIA_INFO_JS;
  }

  return new Promise((resolve, reject) => {
    MediaInfoJS({
      chunkSize: 5 * 1024 * 1024,
      coverData: false,
      format: 'object'
    }, mediainfo => {
      MEDIA_INFO_JS = mediainfo;
      resolve(mediainfo);
    }, error => {
      console.error('[mediainfo.js] failed instantiate', error);
      reject(error);
    })
  });
}

...

async function useMediaInfo () {
  let mediainfo = await getMediaInfoJS();
  ...
}
```

I think this should serve as a valid workaround for this issue since thread safety is not a factor in JS, but the problem is still there
